---
ID: "d92c1ee1-0534-43b1-8a65-b9b8a20af1f4"
Parent: "eb581a84-f22c-4af5-9caf-04883ab86176"
Template: "eb581a84-f22c-4af5-9caf-04883ab86176"
Path: /sitecore/templates/Hackathon/Foundation/Lookup Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "24c44fef-fbc6-4501-b7b1-3e4fcefa313a"
      Hint: value
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220107T115051Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "33bfc4b5-14a9-4407-b448-fda1c95ec798"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220107T115055Z
